## This file is an adapted version of https://svn.nspop.dk:443/svn/components/dds/tags/release-2.2.0rc/compose/development/docker-compose.yml
version: '3.4'

services:      
  openxds-server:
    image: registry.nspop.dk/playground/openxds:0.0.1
    environment:
      - XDS_REGISTRY_HOST={{ OPENTEXT_REGISTRY_HOST }}
      - XDS_REGISTRY_PORT={{ OPENTEXT_REGISTRY_PORT }}
      - XDS_REGISTRY_URL={{ OPENTEXT_REGISTRY_PATH }}
      - XDS_REPOSITORY_UNIQUE_ID={{ OPENXDS_UNIQUE_REPOSITORY_OID }}
      - XDS_HOME_COMMUNITY_ID={{ OPENXDS_COMMUNITY_OID }}
      - XDS_DB_DIALECT=org.hibernate.dialect.MySQLDialect
      - XDS_DB_DRIVER=com.mysql.jdbc.Driver
      - XDS_DB_OPENXDS_URL={{ OPENXDS_DATADB_URL}}
      - XDS_DB_OPENXDS_USERNAME={{ OPENXDS_DATADB_USER }}
      - XDS_DB_OPENXDS_PASSWORD={{ OPENXDS_DATADB_PASS }}
      - XDS_DB_LOGS_URL={{ OPENXDS_LOGDB_URL }}
      - XDS_DB_LOGS_USERNAME={{ OPENXDS_LOGDB_USER }}
      - XDS_DB_LOGS_PASSWORD={{ OPENXDS_LOGDB_PASS }}
      - XARGS=-Xmx128m
      - XDS_LOG_LEVEL=DEBUG
    ports:
      ## open-xds registry port is not exposed since opentext registry is used - "8010:8010"
      ## only expose repository port
      - "{{ OPENXDS_REPOSITORY_PORT }}:8020"
    volumes:
      - ./pack/log/openxds:/logs/