## This file is an adapted version of https://svn.nspop.dk:443/svn/components/dds/tags/release-2.2.0rc/compose/development/docker-compose.yml
version: '3.4'

services:      
  openxds:    
    image: registry.nspop.dk/components/openxds:0.0.1
    environment:
      - XDS_REGISTRY_HOST={{ app_openxds_nxrg_host }}
      - XDS_REGISTRY_PORT={{ app_openxds_nxrg_port }}
      - XDS_REGISTRY_URL={{ app_openxds_nxrg_path }}
      - XDS_REPOSITORY_UNIQUE_ID={{ app_openxds_unique_repository_oid }}
      - XDS_HOME_COMMUNITY_ID={{ app_openxds_home_community }}
      - XDS_DB_DIALECT=org.hibernate.dialect.MySQLDialect
      - XDS_DB_DRIVER=com.mysql.jdbc.Driver
      - XDS_DB_OPENXDS_URL={{ app_openxds_datadb_db_jdbc}}
      - XDS_DB_OPENXDS_USERNAME={{ app_openxds_datadb_username }}
      - XDS_DB_OPENXDS_PASSWORD={{ app_openxds_datadb_password }}
      - XDS_DB_LOGS_URL={{ app_openxds_logdb_db_jdbc }}
      - XDS_DB_LOGS_USERNAME={{ app_openxds_logdb_username }}
      - XDS_DB_LOGS_PASSWORD={{ app_openxds_logdb_password }}
      - XARGS=-Xmx2048m
      - XDS_LOG_LEVEL=DEBUG