version: '3.4'

services:      

  openxds-server-repository:
    build:
      context: ../../.
    image: registry.nspop.dk/components/openxds:snapshot
    depends_on:
      - openxds-repository-db
      - openxds-repository-logs-db
    environment:
      - XDS_REGISTRY_HOST=openxds-server-registry
      - XDS_REGISTRY_PORT=8010
      - XDS_REGISTRY_URL=/axis2/services/xdsregistryb
      - XDS_REPOSITORY_UNIQUE_ID=1.3.6.1.4.1.21367.2010.1.2.1125
      - XDS_HOME_COMMUNITY_ID=urn:oid:1.3.6.1.4.1.21367.2010.1.2.2045
      - XDS_DB_DIALECT=org.hibernate.dialect.MySQLDialect
      - XDS_DB_DRIVER=com.mysql.jdbc.Driver
      - XDS_DB_OPENXDS_URL=jdbc:mysql://openxds-repository-db:3306/openxds
      - XDS_DB_OPENXDS_USERNAME=openxds
      - XDS_DB_OPENXDS_PASSWORD=open123
      - XDS_DB_LOGS_URL=jdbc:mysql://openxds-repository-logs-db:3306/openxdslogs
      - XDS_DB_LOGS_USERNAME=logs
      - XDS_DB_LOGS_PASSWORD=logs123
      - XARGS=-Xmx128m
      - XDS_LOG_LEVEL=DEBUG
    ports:
      - "8020:8020"
    volumes:
      - ./logs:/logs/
 
  openxds-repository-db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openxds
      - MYSQL_USER=openxds
      - MYSQL_PASSWORD=open123
    volumes:
      - ../database/data-db/01_openxds.sql:/docker-entrypoint-initdb.d/01_db.sql
      - ./my.cnf:/etc/mysql/my.cnf
  
  openxds-repository-logs-db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openxdslogs
      - MYSQL_USER=logs
      - MYSQL_PASSWORD=logs123
    volumes:
      - ../database/log-db/01_openxdslogs.sql:/docker-entrypoint-initdb.d/db.sql
      - ./my.cnf:/etc/mysql/my.cnf


  openxds-server-registry:
    build:
      context: ../../.
    image: registry.nspop.dk/components/openxds:snapshot
    depends_on:
      - openxds-db-registry
      - openxds-logs-db-registry
    environment:
      - XDS_HOME_COMMUNITY_ID=urn:oid:1.3.6.1.4.1.21367.2010.1.2.2045
      - XDS_DB_DIALECT=org.hibernate.dialect.MySQLDialect
      - XDS_DB_DRIVER=com.mysql.jdbc.Driver
      - XDS_DB_OPENXDS_URL=jdbc:mysql://openxds-db-registry:3306/openxds
      - XDS_DB_OPENXDS_USERNAME=openxds
      - XDS_DB_OPENXDS_PASSWORD=open123
      - XDS_DB_LOGS_URL=jdbc:mysql://openxds-logs-db-registry:3306/openxdslogs
      - XDS_DB_LOGS_USERNAME=logs
      - XDS_DB_LOGS_PASSWORD=logs123
      - XARGS=-Xmx128m
      - XDS_LOG_LEVEL=DEBUG
      ## The following property is not really needed for the registry, but since the code is not separated, the service will not start unless it exists
      - XDS_REGISTRY_HOST=none
      - XDS_REGISTRY_PORT=8015
      - XDS_REGISTRY_URL=/not/used/from/the/registry/itself
      - XDS_REPOSITORY_UNIQUE_ID=1.3.6.1.4.1.21367.2010.1.2.1125
    ports:
      - "8010:8010"
    volumes:
      - ./logs:/logs/    

  openxds-db-registry:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openxds
      - MYSQL_USER=openxds
      - MYSQL_PASSWORD=open123
    volumes:
      - ../database/data-db/01_openxds.sql:/docker-entrypoint-initdb.d/01_db.sql
      - ./my.cnf:/etc/mysql/my.cnf
  
  openxds-logs-db-registry:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openxdslogs
      - MYSQL_USER=logs
      - MYSQL_PASSWORD=logs123
    volumes:
      - ../database/log-db/01_openxdslogs.sql:/docker-entrypoint-initdb.d/db.sql
      - ./my.cnf:/etc/mysql/my.cnf
