version: '3.4'

services:      

  openxds-repository-server:
    build:
      context: ../../.
    image: registry.nspop.dk/components/openxds:snapshot
    depends_on:
      - openxds-repository-db
      - openxds-repository-logs-db
    environment:
      - XDS_REGISTRY_HOST=nxrg
      - XDS_REGISTRY_PORT=8080
      - XDS_REGISTRY_URL=/nxrg/iti42
      - XDS_REPOSITORY_UNIQUE_ID=1.3.6.1.4.1.21367.2010.1.2.1125
      - XDS_HOME_COMMUNITY_ID=urn:oid:1.3.6.1.4.1.21367.2010.1.2.2045
      - XDS_DB_DIALECT=org.hibernate.dialect.MySQLDialect
      - XDS_DB_DRIVER=com.mysql.jdbc.Driver
      - XDS_DB_OPENXDS_URL=jdbc:mysql://openxds-repository-db:3306/openxds
      - XDS_DB_OPENXDS_USERNAME=openxds
      - XDS_DB_OPENXDS_PASSWORD=open123
      - XDS_DB_LOGS_URL=jdbc:mysql://openxds-repository-logs-db:3306/openxdslogs
      - XDS_DB_LOGS_USERNAME=logs
      - XDS_DB_LOGS_PASSWORD=logs123
      - XARGS=-Xmx128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8110
      - XDS_LOG_LEVEL=DEBUG
    ports:
      - "8020:8020"
      - "8110:8110"
    volumes:
      - ./logs/repository:/logs/
 
  openxds-repository-db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openxds
      - MYSQL_USER=openxds
      - MYSQL_PASSWORD=open123
    volumes:
      - ../database/repository-data-db/01_openxds.sql:/docker-entrypoint-initdb.d/01_db.sql
      - ./my.cnf:/etc/mysql/my.cnf
  
  openxds-repository-logs-db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openxdslogs
      - MYSQL_USER=logs
      - MYSQL_PASSWORD=logs123
    volumes:
      - ../database/log-db/01_openxdslogs.sql:/docker-entrypoint-initdb.d/db.sql
      - ./my.cnf:/etc/mysql/my.cnf

# Nxrg
  nxrgdb:
    image: mariadb:10.1.18
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=nxrg
      - MYSQL_USER=nxrg
      - MYSQL_PASSWORD=nxrg
    ports:
      - "3306:3306"

  cradb:
    image: registry.nspop.dk/platform/cradb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  nxrg:
    image: registry.nspop.dk/components/nxrg:snapshot
    ports:
      - "8080:8080"
    depends_on:
      - cradb
    environment:
      - liquibase_changelog_file=classpath:liquibase-changelog-master.xml
    volumes:
      - ./nxrg/module.xml:/pack/wildfly/modules/sds/nxrg/configuration/main/module.xml
      - ./nxrg/nxrg.properties:/pack/wildfly/modules/sds/nxrg/configuration/main/nxrg.properties
      - ./nxrg/log4j-nxrg-ws.xml:/pack/wildfly/modules/sds/nxrg/configuration/main/log4j-nxrg-ws.xml
      - ./nxrg/log4j-nspslalog-nxrg.properties:/pack/wildfly/modules/sds/nxrg/configuration/main/log4j-nspslalog-nxrg.properties
      - ./nxrg/log4j.properties:/pack/wildfly/modules/sds/nxrg/configuration/main/log4j.properties
      - ./nxrg/nspslalog-nxrg.properties:/pack/wildfly/modules/sds/nxrg/configuration/main/nspslalog-nxrg.properties
      - ./nxrg/crl.skip:/pack/wildfly/modules/system/layers/base/dk/sds/nsp/accesshandler/main/crl.skip
      - ./nxrg/nxrg-ds.xml:/pack/wildfly/standalone/deployments/nxrg-ds.xml
      - ./nxrg/database/ddl:/pack/wildfly/modules/sds/nxrg/configuration/main/ddl:ro
      - ./nxrg/database/test:/pack/wildfly/modules/sds/nxrg/configuration/main/test:ro
      - ./nxrg/database/liquibase-changelog-master.xml:/pack/wildfly/modules/sds/nxrg/configuration/main/liquibase-changelog-master.xml
      - ./nxrg/database/liquibase-changelog-test.xml:/pack/wildfly/modules/sds/nxrg/configuration/main/liquibase-changelog-test.xml
      - ./logs/nxrg:/pack/wildfly/standalone/log